package engine

import (
	"fmt"
)

// TriggerHooks inspects the applied event (e.g., TurnStartedEvent) and evaluates
// any corresponding global or entity-specific hooks, returning the resulting events
// generated by the hooks plus HookRemovedEvents.
func TriggerHooks(state *GameState, trigger Event, eval *LuaEvaluator) ([]Event, error) {
	var events []Event

	// We'll collect all hooks to evaluate
	var activeHooks []Hook

	switch evt := trigger.(type) {
	case *TurnStartedEvent:
		activeHooks = append(activeHooks, collectHooks(state, []string{"next_turn"})...)
		activeHooks = append(activeHooks, collectTargetedHooks(state, evt.ActorID, []string{"next_actor_turn", "next_target_turn"})...)

	case *TurnEndedEvent:
		activeHooks = append(activeHooks, collectHooks(state, []string{"next_turn_end"})...)
		activeHooks = append(activeHooks, collectTargetedHooks(state, evt.ActorID, []string{"next_actor_turn_end", "next_target_turn_end"})...)

	case *RoundStartedEvent:
		activeHooks = append(activeHooks, collectHooks(state, []string{"next_round"})...)
	}

	for _, hook := range activeHooks {
		// Evaluate the hook
		// A hook might be evaluating on behalf of a TargetID
		var actor, target *Entity
		actorID := hook.TargetID
		// Since we don't have the original command context, we'll try to set the context based on TargetID
		if actorID != "" {
			actor = state.Entities[actorID]
			// We might alias target = actor if the hook was declared in targets block,
			// but we just pass actor and target as the exact same entity to be safe.
			target = actor
		}

		ctx := BuildContext(state, actor, target, nil, nil, nil, nil)
		result, err := eval.Eval(hook.Value, ctx)
		if err != nil {
			return nil, fmt.Errorf("hook %s failed: %w", hook.Name, err)
		}

		evts, _ := dispatchTaggedResult(result, actorID, actorID, hook.SourceCommand, state)
		events = append(events, evts...)

		// Remove the hook after execution
		events = append(events, &HookRemovedEvent{
			TargetID: hook.TargetID,
			HookName: hook.Name,
		})
	}

	return events, nil
}

// collectHooks returns all currently registered hooks matching the given types.
// It checks GameState (global) and all Entities.
func collectHooks(state *GameState, types []string) []Hook {
	var results []Hook

	// Check global hooks
	for _, hook := range state.Hooks {
		if containsStr(types, hook.Type) {
			results = append(results, hook)
		}
	}

	// Check all entities
	for _, ent := range state.Entities {
		for _, hook := range ent.Hooks {
			if containsStr(types, hook.Type) {
				results = append(results, hook)
			}
		}
	}

	return results
}

// collectTargetedHooks returns hooks from a specific entity matching the types.
func collectTargetedHooks(state *GameState, targetID string, types []string) []Hook {
	var results []Hook
	ent, ok := state.Entities[targetID]
	if !ok {
		return results
	}
	for _, hook := range ent.Hooks {
		if containsStr(types, hook.Type) {
			results = append(results, hook)
		}
	}
	return results
}

func containsStr(list []string, item string) bool {
	for _, a := range list {
		if a == item {
			return true
		}
	}
	return false
}
